### ISSUE TITLE
Title name

### ISSUE THREAD

**Issue by PrettyTroubles** [PrettyTroubles/Back-pack-plugin#1]
Look into changing the Title name from chest to backpack.

**Comment by RoboMWM** [comment]
Decided to check javadocs since I remembered the `createInventory` method was overloaded with quite a few options.

You can set inventory name on creation. `createInventory(int size, String name)`

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#createInventory(org.bukkit.inventory.InventoryHolder,int,java.lang.String)

**Comment by PrettyTroubles** [comment]
This issue was fixed thank you!
